### ISSUE TITLE
GEE Monkey

### ISSUE THREAD

**Issue by gavinpirrie** [kongdd/gee_packages#2]
Looks great, but I think the link to gee_monkey is broken. Any chance you could fix this?

Thanks in advance,
Gavin

**Comment by kongdd** [comment]
https://github.com/kongdd/gee_monkey

**Comment by geoywa** [comment]
Hi,

The link (https://github.com/kongdd/GEE_Tools/blob/master/gee_monkey.js) seems not working. Could you please give me an update? Thank you! 

Kind regards,
Yunxia

**Comment by kongdd** [comment]
The price is $10 USD. 
https://github.com/kongdd/gee_monkey
